language: python
python:
- 3.5
cache:
  pip: true
addons:
  apt:
    packages:
    - jq
    - moreutils
    - gettext
    - curl
    - httpie
before_install:
  - echo
install:
- pip install nose requests ecs-deploy flake8
script:
- set -eo pipefail
- flake8 .
- bin/build-docker $TRAVIS_BRANCH ${TRAVIS_COMMIT::8} $TRAVIS_BUILD_NUMBER
- docker run -p 5000:5000 -e SECRET_KEY=secret -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY -e AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION -e CONFIG_FILE=$CONFIG_FILE -e CXG_API_BASE=$CXG_API_BASE chanzuckerberg/cellxgene-rest-api:ci &
- for i in {1..90}; do if http :5000/api/v0.1/initialize > /dev/null; then break; else echo "Waiting for server..."; sleep 1; fi; done
- nosetests tests/test_api.py
after_success:
- bash <(curl -s https://codecov.io/bash)
- bin/push-docker
deploy:
- provider: script
  script:
  - ecs deploy stp-staging cellxgene-rest-api-staging --timeout 10000 --tag sha-${TRAVIS_COMMIT::8}
  on:
    branch: master
- provider: script
  script:
  - ecs deploy stp-staging cxg-rest-api-mouse-staging --timeout 10000 --tag sha-${TRAVIS_COMMIT::8}
  on:
    branch: production