language: python
python:
- 3.5
cache:
  pip: true
addons:
  apt:
    packages:
    - jq
    - moreutils
    - gettext
    - curl
before_install:
  - echo
install:
- ls -la ..
- travis_home=`pwd`
- curl -o $travis_home/ecs-cli "https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest"
- echo "$(curl -s https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest.md5) $travis_home/ecs-cli" | md5sum -c -
- chmod +x $travis_home/ecs-cli
- export PATH=$PATH:$travis_home
- echo $PATH
- ls $travis_home
- ecs-cli --version
- pip install nose requests awscli
- make build
- docker run -p 5000:5000 cellxgene python3 cellxgene-rest-api/application.py &
- for i in {1..90}; do if nc -z localhost 5000; then break; else echo "Waiting for server..."; sleep 1; fi; done
script:
- nosetests
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  - provider: script
    script: make deploy
    skip_cleanup: true
    on:
      branch: master
