language: python
python:
- 3.5
cache:
  pip: true
addons:
  apt:
    packages:
    - jq
    - moreutils
    - gettext
    - curl
    - httpie
before_install:
  - echo
install:
- pip install nose requests ecs-deploy
script:
- bin/build-docker $TRAVIS_BRANCH ${TRAVIS_COMMIT::8} $TRAVIS_BUILD_NUMBER
- docker run -p 5000:5000 -e SECRET_KEY=secret -e CXG_API_BASE="http://0.0.0.0:5001/api/v0.1/cells" chanzuckerberg/cellxgene-rest-api:ci &
- for i in {1..90}; do if http :5000/api/v0.1/initialize; then break; else echo "Waiting for server..."; sleep 1; fi; done
- nosetests tests/test_api.py
after_success:
- bash <(curl -s https://codecov.io/bash)
- bin/push-docker
deploy:
- provider: script
  script: ecs deploy stp-staging cellxgene-rest-api-staging --tag sha-${TRAVIS_COMMIT::8}
  on:
    branch: master
