language: python
python:
- 3.5
cache:
  pip: true
addons:
  apt:
    packages:
    - jq
    - moreutils
    - gettext
before_install:
  - echo
install:
- pip install nose requests awscli
- make build
- docker run -p 5000:5000 cellxgene python3 cellxgene-rest-api/application.py &
- for i in {1..90}; do if nc -z localhost 5000; then break; else echo "Waiting for server..."; sleep 1; fi; done
script:
- nosetests
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  - provider: script
    script: make deploy
    skip_cleanup: true
    on:
      branch: master
